#!/bin/bash
#SBATCH -J create
#SBATCH -t 00:30:00
#SBATCH --mem=8G
#SBATCH -o elwe_out/%j.out
#SBATCH -e elwe_err/%j.err
#SBATCH -N 1
#SBATCH -n 1

module load anaconda3
. $ANACONDA_HOME/etc/profile.d/conda.sh
conda activate ba

python -u ./create_model.py -bqm -o 40 -m 6 -t 50 -tb 15 -v 2 -p 850

## Creating
## 20GB for 60x8x60?

## Sampling
## 96GB for 100x10x90? 48GB is not enough
## 48GB for 60x860
## 24GB for 30x6x45