#!/bin/bash
#SBATCH -J kerberos
#SBATCH -t 00:10:00
#SBATCH --mem=5G
#SBATCH -o elwe_out/%j.out
#SBATCH -e elwe_err/%j.err
#SBATCH -N 1

module load anaconda3
. $ANACONDA_HOME/etc/profile.d/conda.sh
conda activate ba

python ./sample_model.py 'models/bqm_5x3(2)x15(10)_c10.pickle' bqm-classic

## Creating
## 20GB for 60x8x60?

## Sampling
## 96GB for 100x10x90? 48GB is not enough
## 48GB for 60x860
## 24GB for 30x6x45
